class IndianArtists {
	public static void main(String[] args) {

		String artist1 = "M. F. Husain";
		System.out.println(artist1);
		String artist2 = "Raja Ravi Varma";
		System.out.println(artist2);
		String artist3 = "Anish Kapoor";
		System.out.println(artist3);
		String artist4 = "Amrita Sher-Gil";
		System.out.println(artist4);
		String artist5 = "S. H. Raza";
		System.out.println(artist5);
		String artist6 = "Subodh Gupta";
		System.out.println(artist6);
		String artist7 = "Tyeb Mehta";
		System.out.println(artist7);
		String artist8 = "Jamini Roy";
		System.out.println(artist8);
		String artist9 = "Bharti Kher";
		System.out.println(artist9);
		String artist10 = "Rabindranath Tagore";
		System.out.println(artist10);
		String artist11 = "F. N. Souza";
		System.out.println(artist11);
		String artist12 = "Atul Dodiya";
		System.out.println(artist12);
		String artist13 = "V. S. Gaitonde";
		System.out.println(artist13);
		String artist14 = "Arpita Singh";
		System.out.println(artist14);
		String artist15 = "Nalini Malani";
		System.out.println(artist15);
		String artist16 = "Ram Kumar";
		System.out.println(artist16);
		String artist17 = "Ganesh Pyne";
		System.out.println(artist17);
		String artist18 = "Satish Gujral";
		System.out.println(artist18);
		String artist19 = "Bhupen Khakhar";
		System.out.println(artist19);
		String artist20 = "Krishen Khanna";
		System.out.println(artist20);
		String artist21 = "Paresh Maity";
		System.out.println(artist21);
		String artist22 = "Gaganendranath Tagore";
		System.out.println(artist22);
		String artist23 = "A. Ramachandran";
		System.out.println(artist23);
		String artist24 = "Manjit Bawa";
		System.out.println(artist24);
		String artist25 = "Reena Saini Kallat";
		System.out.println(artist25);
		String artist26 = "Nandalal Bose";
		System.out.println(artist26);
		String artist27 = "Rameshwar Broota";
		System.out.println(artist27);
		String artist28 = "Jogen Chowdhury";
		System.out.println(artist28);
		String artist29 = "Benode Behari Mukherjee";
		System.out.println(artist29);
		String artist30 = "Nasreen Mohamedi";
		System.out.println(artist30);
		String artist31 = "Zarina Hashmi";
		System.out.println(artist31);
		String artist32 = "Vivan Sundaram";
		System.out.println(artist32);
		String artist33 = "Sudhir Patwardhan";
		System.out.println(artist33);
		String artist34 = "Thota Vaikuntam";
		System.out.println(artist34);
		String artist35 = "Laxma Goud";
		System.out.println(artist35);
		String artist36 = "Ravinder Reddy";
		System.out.println(artist36);
		String artist37 = "N. S. Harsha";
		System.out.println(artist37);
		String artist38 = "Akbar Padamsee";
		System.out.println(artist38);
		String artist39 = "K. G. Subramanyan";
		System.out.println(artist39);
		String artist40 = "K. H. Ara";
		System.out.println(artist40);
		String artist41 = "Sadanand Bakre";
		System.out.println(artist41);
		String artist42 = "Mukul Dey";
		System.out.println(artist42);
		String artist43 = "Bikash Bhattacharjee";
		System.out.println(artist43);
		String artist44 = "Anjolie Ela Menon";
		System.out.println(artist44);
		String artist45 = "Gulam Mohammed Sheikh";
		System.out.println(artist45);
		String artist46 = "Shilpa Gupta";
		System.out.println(artist46);
		String artist47 = "Raqib Shaw";
		System.out.println(artist47);
		String artist48 = "Jitish Kallat";
		System.out.println(artist48);
		String artist49 = "Ramkinkar Baij";
		System.out.println(artist49);
		String artist50 = "Abanindranath Tagore";
		System.out.println(artist50);

	}
}