class ByteSwimmer{
	public static void main(String[] args){
		byte temp = 30;
		System.out.println(temp);
		temp = 25;
		System.out.println(temp);
		byte age = 30;
		System.out.println(age);
		age = 55;
		System.out.println(age);
		byte week = 67;
		System.out.println(week);
		week = 55;
		System.out.println(week);
		byte month = 12;
		System.out.println(month);
		month = 7;
		System.out.println(month);
		byte min = 14;
		System.out.println(min);
		min = 33;
		System.out.println(min);
		byte sec = 10;
		System.out.println(sec);
		sec = 37;
		System.out.println(sec);
		byte hour = 18;
		System.out.println(hour);
		hour = 33;
		System.out.println(hour);
        byte millisec= 14;
		System.out.println(millisec);
		millisec = 30;
		System.out.println(millisec);
		byte microsec = 19;
		System.out.println(microsec);
		microsec = 39;
		System.out.println(microsec);
		byte c1 = 12;
		System.out.println(c1);
		c1 = 31;
		System.out.println(c1);
		byte a1 = 99;
		System.out.println(a1);
		a1 = 55;
		System.out.println(a1);
		byte a2 = 90;
		System.out.println(a2);
		a2 = 65;
		System.out.println(a2);
		byte a3 = 29;
		System.out.println(a3);
		a3 = 85;
		System.out.println(a3);
		byte a4 = 89;
		System.out.println(a4);
		a4 = 85;
		System.out.println(a4);
		byte a5 = 79;
		System.out.println(a5);
		a5 = 55;
		System.out.println(a5);
		byte a6 = 99;
		System.out.println(a6);
		a6 = 45;
		System.out.println(a6);
		byte a7 = 59;
		System.out.println(a7);
		a7 = 15;
		System.out.println(a7);
		byte a8 = 69;
		System.out.println(a8);
		a8 = 35;
		System.out.println(a8);
		byte a9 = 99;
		System.out.println(a9);
		a9 = 55;
		System.out.println(a9);
		byte a10 = 79;
		System.out.println(a10);
		a10 = 35;
		System.out.println(a10);
		}
}

