class BooleanSwimmer{
	public static void main(String[] args){
		boolean isActive = true;
		System.out.println(isActive);
		isActive = false;
		System.out.println(isActive);
		boolean isLoggedIn = false;
		System.out.println(isLoggedIn);
		isLoggedIn = false;
		System.out.println(isLoggedIn);
		boolean isVerified = true;
		System.out.println(isVerified);
		isVerified = false;
		System.out.println(isVerified);
		boolean isEnabled = false;
		System.out.println(isEnabled);
		isEnabled = true;
		System.out.println(isEnabled);
		boolean isBlocked = true;
		System.out.println(isBlocked);
		isBlocked = false;
		System.out.println(isBlocked);
		boolean hasPermission = false;
		System.out.println(hasPermission);
		hasPermission = true;
		System.out.println(hasPermission);
		boolean hasAcess = true;
		System.out.println(hasAcess);
		hasAcess = false;
		System.out.println(hasAcess);
		boolean hasPaid = false;
		System.out.println(hasPaid);
		hasPaid = true;
		System.out.println(hasPaid);
		boolean hasDiscount = true;
		System.out.println(hasDiscount);
		hasDiscount = false;
		System.out.println(hasDiscount);
		boolean isEmailVerified = false;
		System.out.println(isEmailVerified);
		isEmailVerified = true;
		System.out.println(isEmailVerified);
		boolean isMobileVerified = true;
		System.out.println(isMobileVerified);
		isMobileVerified = false;
		System.out.println(isMobileVerified);
		boolean isAccountLocked = false;
		System.out.println(isAccountLocked);
		isAccountLocked = false;
		System.out.println(isAccountLocked);
		boolean isPasswordValid = true;
		System.out.println(isPasswordValid);
		isPasswordValid = false;
		System.out.println(isPasswordValid);
		boolean isTwoFactorEnabled = false;
		System.out.println(isTwoFactorEnabled);
		isTwoFactorEnabled = true;
		System.out.println(isTwoFactorEnabled);
		boolean isPaymentSucessful = true;
		System.out.println(isPaymentSucessful);
		isPaymentSucessful = false;
		System.out.println(isPaymentSucessful);
		boolean isOderPlaced = false;
		System.out.println(isOderPlaced);
		isOderPlaced = true;
		System.out.println(isOderPlaced);
		boolean isDelivered = true;
		System.out.println(isDelivered);
		isDelivered = false;
		System.out.println(isDelivered);
		boolean isCancelled = false;
		System.out.println(isCancelled);
		isCancelled = true;
		System.out.println(isCancelled);
		boolean isDarkModeEnabled = true;
		System.out.println(isDarkModeEnabled);
		isDarkModeEnabled = false;
		System.out.println(isDarkModeEnabled);
		boolean isLocationEnabled = false;
		System.out.println(isLocationEnabled);
		isLocationEnabled = true;
		System.out.println(isLocationEnabled);
	}
}
