class ProductRunner{
	
	public static void main(String[] args){
		
		Product product1 = new Product("Bottle", "Fibers", "2-3-2003", 100.0, ProductType.FIBER_PRODUCTS,"BalajiShore", ProductWarranty.TEN_YEARS, null,"1", "India");
		Product product2 = new Product("Oil", "Liquid", "12-6-2007", 200.0, ProductType.OIL_PRODUCTS,"Fortune", ProductWarranty.TWO_YEARS, "2","2", "England");
		Product product3 = new Product("Milk", "Dairy", "22-8-2009", 50.0, ProductType.MILK_PRODUCTS,"Nandini", ProductWarranty.ONE_YEAR, "3","9", "USA");
		Product product4 = new Product("Soap", "Cosmetic", "8-8-2024", 30.0, ProductType.COSMETICS,"Lux", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product5 = new Product("Shampoo", "Cosmetic", "22-8-2002", 150.0, ProductType.COSMETICS,"Dove", ProductWarranty.THREE_YEARS, "3","8", "Japan");
		Product product6 = new Product("Rice", "food", "29-8-2009", 90.0, ProductType.GROCERIES,"basmati", ProductWarranty.TEN_YEARS, "1","2", "Germany");
		Product product7 = new Product("Wheat", "food", "1-2-2006", 60.0, ProductType.GROCERIES,"ashirvad", ProductWarranty.ONE_YEAR, "4","3", "France");
		Product product8 = new Product("Cheese", "Dairy", "28-8-2009", 50.0, ProductType.MILK_PRODUCTS,"Manasa", ProductWarranty.TWO_YEARS, "8","2", "Canada");
		Product product9 = new Product("HAir oil", "Liquid", "22-8-2009", 100.0, ProductType.OIL_PRODUCTS,"Parachute", ProductWarranty.ONE_YEAR, "2","5", "Australia");
		Product product10 = new Product("Face Cream", "cosmetic", "8-8-2009", 50.0, ProductType.COSMETICS,"Ponds", ProductWarranty.TEN_YEARS, "3","3", "brazil");
		Product product11 = new Product("Talc Powder", "cosmetic", "2-8-2009", 90.0, ProductType.COSMETICS,"Ponds", ProductWarranty.THREE_YEARS, "3","7", "south korea");
		Product product12 = new Product("Sugar", "groceries", "12-8-2009", 50.0, ProductType.GROCERIES,"Supermarket", ProductWarranty.ONE_YEAR, "6","3", "singapore");
		Product product13 = new Product("Salt", "groceries", "29-8-2009", 10.0, ProductType.GROCERIES,"supermarket", ProductWarranty.TWO_YEARS, "3","9", "malaysia");
		Product product14 = new Product("Dal", "groceries", "1-8-2006", 90.0, ProductType.GROCERIES,"supermarket", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product15 = new Product("Curd", "Dairy", "2-8-2004", 100.0, ProductType.MILK_PRODUCTS,"nandini", ProductWarranty.ONE_YEAR, "4","8", "Saudi arabia");
		Product product16 = new Product("paneer", "Dairy", "9-8-2009", 500.0, ProductType.MILK_PRODUCTS,"DMARt", ProductWarranty.ONE_YEAR, "3","1", "nepal");
		Product product17 = new Product("sunflower oil", "liquid", "3-6-2005", 300.0, ProductType.OIL_PRODUCTS,"Mart", ProductWarranty.TEN_YEARS, "12","3", "sri lanka");
		Product product18 = new Product("cocount oil", "liquid", "2-8-2009", 200.0, ProductType.OIL_PRODUCTS,"Mart", ProductWarranty.THREE_YEARS, "2","6", "pakistan");
		Product product19 = new Product("Hair oil", "liquid", "1-8-2005", 530.0, ProductType.OIL_PRODUCTS,"mart", ProductWarranty.TWO_YEARS, "8","4", "India");
		Product product20 = new Product("Olive oil", "liquid", "26-8-2009", 510.0, ProductType.OIL_PRODUCTS,"Reliance", ProductWarranty.THREE_YEARS, "9","3", "England");
		Product product21 = new Product("Plastic chair", "fibers", "2-4-2009", 120.0, ProductType.FIBER_PRODUCTS,"Reliance", ProductWarranty.ONE_YEAR, "6","3", "USA");
		Product product22 = new Product("BUCKEt", "fibers", "25-8-2006", 50.0, ProductType.FIBER_PRODUCTS,"Reliance", ProductWarranty.TWO_YEARS, "2","3", "China");
		Product product23 = new Product("container", "fibers", "8-8-2009", 100.0, ProductType.FIBER_PRODUCTS,"Reliance", ProductWarranty.ONE_YEAR, "1","3", "germany");
		Product product24 = new Product("Facewash", "cosmetic", "9-8-2000", 90.0, ProductType.COSMETICS,"HIMAlaya", ProductWarranty.ONE_YEAR, "9","3", "arabia");
		Product product25 = new Product("BODy lotion", "cosmetic", "8-8-2009", 80.0, ProductType.COSMETICS,"PILigrim", ProductWarranty.THREE_YEARS, "9","3", "thailand");
		Product product26 = new Product("Hand wash", "COSMETICS", "7-8-2009", 70.0, ProductType.COSMETICS,"Dettol", ProductWarranty.TEN_YEARS, "9","9", "russia");
		Product product27 = new Product("TOothPaste", "cosmetic", "6-8-2009", 60.0, ProductType.COSMETICS,"colgate", ProductWarranty.THREE_YEARS, "2","3", "pakistan");
		Product product28 = new Product("TOoth brush", "cosmetic", "5-8-2009", 50.0, ProductType.COSMETICS,"ORALB", ProductWarranty.TWO_YEARS, "9","3", "korea");
		Product product29 = new Product("Maida", "Food", "4-8-2009", 10.0, ProductType.GROCERIES,"ashirvad", ProductWarranty.ONE_YEAR, "4","9", "malaysia");
		Product product30 = new Product("Rava", "Food", "3-8-2009", 20.0, ProductType.GROCERIES,"LocalMart", ProductWarranty.THREE_YEARS, "9","2", "bangladesh");
		Product product31 = new Product("Corn Flour", "Food", "2-8-2009", 30.0, ProductType.GROCERIES,"Urban", ProductWarranty.ONE_YEAR, "3","4", "france");
		Product product32 = new Product("Ice cream", "Dairy", "1-8-2009", 40.0, ProductType.MILK_PRODUCTS,"Amul", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product33 = new Product("ghee", "Diary", "22-8-2009", 50.0, ProductType.MILK_PRODUCTS,"Nandhini", ProductWarranty.TEN_YEARS, "6","3", "USa");
		Product product34 = new Product("Butter Milk", "Diary", "14-8-2009", 60.0, ProductType.MILK_PRODUCTS,"Nandhini", ProductWarranty.TEN_YEARS, "5","3", "china");
		Product product35 = new Product("Mustard oil", "Liquid", "15-8-2009", 50.0, ProductType.OIL_PRODUCTS,"fortune", ProductWarranty.TEN_YEARS, "6","3", "japan");
		Product product36 = new Product("Groundnut oil", "liquid", "16-8-2009", 80.0, ProductType.OIL_PRODUCTS,"freedom", ProductWarranty.TEN_YEARS, "5","3", "germany");
		Product product37 = new Product("Engine oil", "liquid", "17-8-2009", 90.0, ProductType.OIL_PRODUCTS,"castrol", ProductWarranty.TEN_YEARS, "1","3", "france");
		Product product38 = new Product("plastic table", "fibers", "18-8-2009", 500.0, ProductType.FIBER_PRODUCTS,"Local store", ProductWarranty.TEN_YEARS, "6","3", "canada");
		Product product39 = new Product("Plastic Mug", "fibers", "19-8-2009", 100.0, ProductType.FIBER_PRODUCTS,"Local", ProductWarranty.TEN_YEARS, "6","3", "australia");
		Product product40 = new Product("water tank", "fibers", "20-8-2009", 50.0, ProductType.FIBER_PRODUCTS,"LOcal", ProductWarranty.TEN_YEARS, "6","1", "brazil");
		Product product41 = new Product("Dustbin", "fibers", "21-8-2009", 90.0, ProductType.FIBER_PRODUCTS,"local", ProductWarranty.TEN_YEARS, "9","3", "russia");
		Product product42 = new Product("face scrub", "cosmetic", "23-8-2009", 150.0, ProductType.COSMETICS,"Everyuth", ProductWarranty.TEN_YEARS, "4","3", "south korea");
		Product product43 = new Product("sunscreen", "cosmetic", "24-8-2009", 500.0, ProductType.COSMETICS,"PIligrim", ProductWarranty.TEN_YEARS, "9","3", "singapore");
		Product product44 = new Product("Lip Balm", "cosmetic", "25-8-2009", 10.0, ProductType.COSMETICS,"nivea", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product45 = new Product("Deodrant", "cosmetic", "26-8-2009", 20.0, ProductType.COSMETICS,"axe", ProductWarranty.THREE_YEARS, "6","1", "thailand");
		Product product46 = new Product("perfume", "cosmetic", "27-8-2009", 30.0, ProductType.COSMETICS,"Fogg", ProductWarranty.ONE_YEAR, "9","3", "saudi arabia");
		Product product47 = new Product("BEsan", "Food", "28-8-2009", 40.0, ProductType.GROCERIES,"local", ProductWarranty.TEN_YEARS, "4","3", "nepal");
		Product product48 = new Product("Oats", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"urban", ProductWarranty.TWO_YEARS, "6","3", "sri lanka");
		Product product49 = new Product("CornFlakes", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"urban", ProductWarranty.TWO_YEARS, "6","3", "bangladesh");
		Product product50 = new Product("Honey", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"dabour", ProductWarranty.TWO_YEARS, "6","3", "pakistan");
		Product product51 = new Product("Fan", "electronics", "4-5-2005",80.0, ProductType.ELECTRONICS, "LIVO", ProductWarranty.TEN_YEARS, "4", "2", "INDIA");
        Product product52 = new Product("poha", "Food", "3-8-2009", 20.0, ProductType.GROCERIES,"LocalMart", ProductWarranty.THREE_YEARS, "9","2", "bangladesh");
		Product product53 = new Product("rice Flour", "Food", "2-8-2009", 30.0, ProductType.GROCERIES,"Urban", ProductWarranty.ONE_YEAR, "3","4", "france");
		Product product54 = new Product("onitment cream", "medicines", "1-1-2009", 40.0, ProductType.MEDICINES,"cool", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product55 = new Product("ghee", "Diary", "22-8-2009", 50.0, ProductType.MILK_PRODUCTS,"doodle", ProductWarranty.TEN_YEARS, "6","3", "USa");
		Product product56 = new Product("Butter Milk", "Diary", "14-8-2009", 60.0, ProductType.MILK_PRODUCTS,"amul", ProductWarranty.TEN_YEARS, "5","3", "china");
		Product product57 = new Product("Mustard oil", "Liquid", "15-8-2009", 50.0, ProductType.OIL_PRODUCTS,"sunflower", ProductWarranty.TEN_YEARS, "6","3", "japan");
		Product product58 = new Product("Groundnut oil", "liquid", "16-8-2009", 80.0, ProductType.OIL_PRODUCTS,"sunflower", ProductWarranty.TEN_YEARS, "5","3", "germany");
		Product product59 = new Product("Engine oil", "liquid", "17-8-2009", 90.0, ProductType.OIL_PRODUCTS,"castrol and other", ProductWarranty.TEN_YEARS, "1","3", "france");
		Product product60 = new Product("plastic table", "fibers", "18-8-2009", 500.0, ProductType.FIBER_PRODUCTS,"urban store", ProductWarranty.TEN_YEARS, "6","3", "canada");
		Product product61 = new Product("Plastic Mug", "fibers", "19-8-2009", 100.0, ProductType.FIBER_PRODUCTS,"urban", ProductWarranty.TEN_YEARS, "6","3", "australia");
		Product product62 = new Product("water tank", "fibers", "20-8-2009", 50.0, ProductType.FIBER_PRODUCTS,"Sentex", ProductWarranty.TEN_YEARS, "6","1", "brazil");
		Product product63 = new Product("Dustbin", "fibers", "21-8-2009", 90.0, ProductType.FIBER_PRODUCTS,"plastics", ProductWarranty.TEN_YEARS, "9","3", "russia");
		Product product64 = new Product("face scrub", "cosmetic", "23-8-2009", 150.0, ProductType.COSMETICS,"goldenglow", ProductWarranty.TEN_YEARS, "4","3", "south korea");
		Product product65 = new Product("sunscreen", "cosmetic", "24-8-2009", 500.0, ProductType.COSMETICS,"ponds", ProductWarranty.TEN_YEARS, "9","3", "singapore");
		Product product66 = new Product("Lip Balm", "cosmetic", "25-8-2009", 10.0, ProductType.COSMETICS,"ponds", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product67 = new Product("Deodrant", "cosmetic", "26-8-2009", 20.0, ProductType.COSMETICS,"rexona", ProductWarranty.THREE_YEARS, "6","1", "thailand");
		Product product68 = new Product("perfume", "cosmetic", "27-8-2009", 30.0, ProductType.COSMETICS,"belveta", ProductWarranty.ONE_YEAR, "9","3", "saudi arabia");
		Product product69 = new Product("BEsan", "Food", "28-8-2009", 40.0, ProductType.GROCERIES,"urban", ProductWarranty.TEN_YEARS, "4","3", "nepal");
		Product product70 = new Product("Oats", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"local", ProductWarranty.TWO_YEARS, "6","3", "sri lanka");
		Product product71 = new Product("CornFlakes", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"localstore", ProductWarranty.TWO_YEARS, "6","3", "bangladesh");
		Product product72 = new Product("Honey", "Food", "29-8-2009", 50.0, ProductType.GROCERIES,"honeymill", ProductWarranty.TWO_YEARS, "6","3", "pakistan");
		Product product73 = new Product("sunscreen", "cosmetic", "24-8-2009", 200.0, ProductType.COSMETICS,"nuface", ProductWarranty.TEN_YEARS, "9","3", "india");
		Product product74 = new Product("sunscreen", "cosmetic", "24-8-2009", 100.0, ProductType.COSMETICS,"hyphen", ProductWarranty.TEN_YEARS, "9","3", "russia");
		Product product75 = new Product("sunscreen", "cosmetic", "24-8-2009", 500.0, ProductType.COSMETICS,"dotandkey", ProductWarranty.TEN_YEARS, "9","3", "germany");
		Product product76 = new Product("sunscreen", "cosmetic", "24-8-2009", 1500.0, ProductType.COSMETICS,"garnier", ProductWarranty.TEN_YEARS, "9","3", "singapore");
		Product product77 = new Product("perfume", "cosmetic", "27-8-2009", 310.0, ProductType.COSMETICS,"afnan", ProductWarranty.ONE_YEAR, "9","3", "saudi arabia");
		Product product78 = new Product("perfume", "cosmetic", "27-8-2009", 30.0, ProductType.COSMETICS,"armaf", ProductWarranty.ONE_YEAR, "9","3", "australia");
		Product product79 = new Product("perfume", "cosmetic", "27-8-2009", 30.0, ProductType.COSMETICS,"burberry", ProductWarranty.ONE_YEAR, "9","3", "saudi arabia");
		Product product80 = new Product("perfume", "cosmetic", "27-8-2009", 30.0, ProductType.COSMETICS,"bebe", ProductWarranty.ONE_YEAR, "9","3", "south korea");
		Product product81 = new Product("Groundnut oil", "liquid", "16-8-2009", 80.0, ProductType.OIL_PRODUCTS,"ruchgold", ProductWarranty.TEN_YEARS, "5","3", "germany");
		Product product82 = new Product("Soap", "Cosmetic", "8-8-2026", 30.0, ProductType.COSMETICS,"medimix", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product83 = new Product("Soap", "Cosmetic", "8-8-2024", 150.0, ProductType.COSMETICS,"gramflour", ProductWarranty.TWO_YEARS, "9","3", "russia");
		Product product84 = new Product("Soap", "Cosmetic", "8-8-2024", 120.0, ProductType.COSMETICS,"rexona", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product85 = new Product("Soap", "Cosmetic", "8-8-2024", 130.0, ProductType.COSMETICS,"dettol", ProductWarranty.TWO_YEARS, "9","3", "australia");
		Product product86 = new Product("Soap", "Cosmetic", "8-8-2024", 30.0, ProductType.COSMETICS,"mysoresandal", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product87 = new Product("Soap", "Cosmetic", "8-8-2024", 170.0, ProductType.COSMETICS,"acnescar", ProductWarranty.TWO_YEARS, "9","3", "thailand");
		Product product88 = new Product("Soap", "Cosmetic", "8-8-2024", 190.0, ProductType.COSMETICS,"dove", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product89 = new Product("Soap", "Cosmetic", "8-8-2024", 20.0, ProductType.COSMETICS,"santoor", ProductWarranty.TWO_YEARS, "9","3", "malaysia");
		Product product90 = new Product("Shampoo", "Cosmetic", "8-8-2024", 10.0, ProductType.COSMETICS,"tresme", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product91 = new Product("Shampoo", "Cosmetic", "8-8-2024", 30.0, ProductType.COSMETICS,"meera", ProductWarranty.TWO_YEARS, "9","3", "singapore");
		Product product92 = new Product("Shampoo", "Cosmetic", "8-8-2024", 20.0, ProductType.COSMETICS,"karthika", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product93 = new Product("Shampoo", "Cosmetic", "8-8-2024", 30.0, ProductType.COSMETICS,"keshkanthi", ProductWarranty.TWO_YEARS, "9","3", "germany");
		Product product94 = new Product("Shampoo", "Cosmetic", "8-8-2024", 40.0, ProductType.COSMETICS,"headandshoulder", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product95 = new Product("Shampoo", "Cosmetic", "8-8-2024", 60.0, ProductType.COSMETICS,"clear", ProductWarranty.TWO_YEARS, "9","3", "China");
		Product product96 = new Product("Talc Powder", "cosmetic", "2-8-2009", 90.0, ProductType.COSMETICS,"cool", ProductWarranty.THREE_YEARS, "3","7", "south korea");
		Product product97 = new Product("paneer", "Dairy", "9-8-2009", 200.0, ProductType.MILK_PRODUCTS,"reliance", ProductWarranty.ONE_YEAR, "3","1", "nepal");
		Product product98 = new Product("paneer", "Dairy", "9-8-2009", 50.0, ProductType.MILK_PRODUCTS,"vishalmarket", ProductWarranty.ONE_YEAR, "3","1", "nepal");
		Product product99 = new Product("paneer", "Dairy", "9-8-2009", 10.0, ProductType.MILK_PRODUCTS,"amul", ProductWarranty.ONE_YEAR, "3","1", "nepal");
		Product product100 = new Product("paneer", "Dairy", "9-8-2009", 500.0, ProductType.MILK_PRODUCTS,"paneerhub", ProductWarranty.ONE_YEAR, "3","1", "nepal");
		Product product101 = new Product("Lip Balm", "cosmetic", "25-8-2009", 109.0, ProductType.COSMETICS,"nivea", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product102 = new Product("Lip Balm", "cosmetic", "25-8-2009", 100.0, ProductType.COSMETICS,"himalaya", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product103 = new Product("Lip Balm", "cosmetic", "25-8-2009", 106.0, ProductType.COSMETICS,"bioderma", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product104 = new Product("Lip Balm", "cosmetic", "25-8-2009", 104.0, ProductType.COSMETICS,"derma", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product105 = new Product("Lip Balm", "cosmetic", "25-8-2009", 102.0, ProductType.COSMETICS,"piligrim", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product106 = new Product("Lip Balm", "cosmetic", "25-8-2009", 101.0, ProductType.COSMETICS,"vaseline", ProductWarranty.TEN_YEARS, "6","6", "malaysia");
		Product product107 = new Product("rice", "Food", "2-8-2009", 10.0, ProductType.GROCERIES,"Urban", ProductWarranty.ONE_YEAR, "3","4", "france");
		Product product108 = new Product("rice", "Food", "2-8-2009", 130.0, ProductType.GROCERIES,"bullet rice", ProductWarranty.ONE_YEAR, "3","4", "germany");
		Product product109 = new Product("rice Flour", "Food", "2-8-2009", 20.0, ProductType.GROCERIES,"basmati", ProductWarranty.ONE_YEAR, "3","4", "france");
		Product product110= new Product("Dal", "groceries", "1-8-2006", 190.0, ProductType.GROCERIES,"market", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product111 = new Product("Dal", "groceries", "1-8-2006", 10.0, ProductType.GROCERIES,"more", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product112 = new Product("moogDal", "groceries", "1-8-2006", 390.0, ProductType.GROCERIES,"supermarket", ProductWarranty.THREE_YEARS, "1","2", "russia");
		Product product113 = new Product("pen", "groceries", "1-8-2006", 910.0, ProductType.GROCERIES,"supermarket", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product114 = new Product("books", "groceries", "1-8-2006", 290.0, ProductType.GROCERIES,"supermarket", ProductWarranty.THREE_YEARS, "1","2", "England");
		Product product115 = new Product("wire", "electronics", "1-8-2006", 290.0, ProductType.ELECTRONICS,"dell", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product116 = new Product("tv", "electronics", "1-8-2006", 130.0, ProductType.ELECTRONICS,"zoom", ProductWarranty.THREE_YEARS, "1","2", "india");
		Product product117 = new Product("tv", "electronics", "1-8-2006", 230.0, ProductType.ELECTRONICS,"doom", ProductWarranty.THREE_YEARS, "1","2", "singapore");
		Product product118 =new Product("fridge", "electronics", "1-8-2006", 30.0, ProductType.ELECTRONICS,"vguard", ProductWarranty.THREE_YEARS, "1","2", "south korea");
		Product product119 = new Product("washinemachine", "electronics", "1-8-2006", 130.0, ProductType.ELECTRONICS,"Lg", ProductWarranty.THREE_YEARS, "1","2", "newzland");
		Product product120 = new Product("washinemachine", "electronics", "1-8-2006", 30.0, ProductType.ELECTRONICS,"sumsung", ProductWarranty.THREE_YEARS, "1","2", "chicago");
		Product product121= new Product("washinemachine", "electronics", "1-8-2006", 130.0, ProductType.ELECTRONICS,"wobble", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product122 = new Product("tv", "electronics", "1-8-2006", 230.0, ProductType.ELECTRONICS,"truvision", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product123= new Product("pendrive", "electronics", "1-8-2006", 230.0, ProductType.ELECTRONICS,"dell", ProductWarranty.THREE_YEARS, "1","2", "germany");
		Product product124 = new Product("mouse", "electronics", "1-8-2006", 430.0, ProductType.ELECTRONICS,"dell", ProductWarranty.THREE_YEARS, "1","2", "france");
		Product product125= new Product("laptop", "electronics", "1-8-2006", 10000.0, ProductType.ELECTRONICS,"hp", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product126= new Product("keyboard", "electronics", "1-8-2006", 30.0, ProductType.ELECTRONICS,"dell", ProductWarranty.THREE_YEARS, "1","2", "newzland");
		Product product127 = new Product("light", "electronics", "1-8-2006", 30.0, ProductType.ELECTRONICS,"lightbulb", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product128= new Product("Ice cream", "Dairy", "1-8-2009", 40.0, ProductType.MILK_PRODUCTS,"butterstoch", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product129 = new Product("eggpuff", "bakery", "1-8-2009", 40.0, ProductType.BAKERY,"BAKEWORLD", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product130= new Product("vegPuff", "bakery", "1-8-2009", 40.0, ProductType.BAKERY,"BAKEWORLD", ProductWarranty.TWO_YEARS, "5","3", "INDIA");
		Product product131 = new Product("jucie", "Bakery", "1-8-2009", 40.0, ProductType.BAKERY,"jeera", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product132 = new Product("jucie", "Bakery", "1-8-2009", 40.0, ProductType.BAKERY,"milkshake", ProductWarranty.TWO_YEARS, "5","3", "korea");
		Product product133 = new Product("jeera", "groceries", "1-8-2006", 190.0, ProductType.GROCERIES,"market", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product134 = new Product("mustard", "groceries", "1-8-2006", 190.0, ProductType.GROCERIES,"market", ProductWarranty.THREE_YEARS, "1","2", "russia");
		Product product135 = new Product("peanut","groceries", "1-8-2006", 190.0, ProductType.GROCERIES,"market", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product136= new Product("peas", "groceries", "1-8-2006", 190.0, ProductType.GROCERIES,"market", ProductWarranty.THREE_YEARS, "1","2", "thailand");
		Product product137 = new Product("Almand oil", "Liquid", "22-8-2009", 100.0, ProductType.OIL_PRODUCTS,"Parachute", ProductWarranty.ONE_YEAR, "2","5", "Australia");
	
		
		product1.displayInfo();
		product2.displayInfo();
		product3.displayInfo();    
		product4.displayInfo();
		product5.displayInfo();
		product6.displayInfo();
		product7.displayInfo();
		product8.displayInfo();
		product9.displayInfo();
		product10.displayInfo();
		product11.displayInfo();
		product12.displayInfo();
		product13.displayInfo();
		product14.displayInfo();
		product15.displayInfo();
		product16.displayInfo();
		product17.displayInfo();
		product18.displayInfo();
		product19.displayInfo();
		product20.displayInfo();
		product21.displayInfo();
		product22.displayInfo();
		product23.displayInfo();
		product24.displayInfo();
		product25.displayInfo();
		product26.displayInfo();
		product27.displayInfo();
		product28.displayInfo();
		product29.displayInfo();
		product30.displayInfo();
		product31.displayInfo();
		product32.displayInfo();
		product33.displayInfo();
		product34.displayInfo();
		product35.displayInfo();
		product36.displayInfo();
		product37.displayInfo();
		product38.displayInfo();
		product39.displayInfo();
		product40.displayInfo();
		product41.displayInfo();
		product42.displayInfo();
		product43.displayInfo();
		product44.displayInfo();
		product45.displayInfo();
		product46.displayInfo();
		product47.displayInfo();
		product48.displayInfo();
		product49.displayInfo();
		product50.displayInfo();
		product51.displayInfo();
		product52.displayInfo();
		product53.displayInfo();
		product54.displayInfo();
		product55.displayInfo();
		product56.displayInfo();
		product57.displayInfo();
		product58.displayInfo();
		product59.displayInfo();
		product60.displayInfo();
		product61.displayInfo();
		product62.displayInfo();
		product63.displayInfo();
		product64.displayInfo();
		product65.displayInfo();
		product66.displayInfo();
		product67.displayInfo();
		product68.displayInfo();
		product69.displayInfo();
		product70.displayInfo();
		product71.displayInfo();
		product72.displayInfo();
		product73.displayInfo();
		product74.displayInfo();
		product75.displayInfo();
		product76.displayInfo();
		product77.displayInfo();
		product78.displayInfo();
		product79.displayInfo();
		product80.displayInfo();
		product81.displayInfo();
		product82.displayInfo();
		product83.displayInfo();
		product84.displayInfo();
		product85.displayInfo();
		product86.displayInfo();
		product87.displayInfo();
		product88.displayInfo();
		product89.displayInfo();
		product90.displayInfo();
		product91.displayInfo();
		product92.displayInfo();
		product93.displayInfo();
		product94.displayInfo();
		product95.displayInfo();
		product96.displayInfo();
		product97.displayInfo();
		product98.displayInfo();
		product99.displayInfo();
		product100.displayInfo();
		product101.displayInfo();
		product102.displayInfo();
		product103.displayInfo();
		product104.displayInfo();
		product105.displayInfo();
		product106.displayInfo();
		product107.displayInfo();
		product108.displayInfo();
		product109.displayInfo();
		product110.displayInfo();
		product111.displayInfo();
		product112.displayInfo();
		product113.displayInfo();
		product114.displayInfo();
		product115.displayInfo();
		product116.displayInfo();
		product117.displayInfo();
		product118.displayInfo();
		product119.displayInfo();
		product120.displayInfo();
		product121.displayInfo();
		product122.displayInfo();
		product123.displayInfo();
		product124.displayInfo();
		product125.displayInfo();
		product126.displayInfo();
		product127.displayInfo();
		product128.displayInfo();
		product129.displayInfo();
		product130.displayInfo();
		product131.displayInfo();
		product132.displayInfo();
		product133.displayInfo();
		product134.displayInfo();
		product135.displayInfo();
		product136.displayInfo();
		product137.displayInfo();
		
		
		
		Product[] products = new Product[137];
		ProductStore productStore = new ProductStore(products);
		productStore.saveProductStore(product1);
		productStore.saveProductStore(product2);
		productStore.saveProductStore(product3);
		productStore.saveProductStore(product4);
		productStore.saveProductStore(product5);
		productStore.saveProductStore(product6);
		productStore.saveProductStore(product7);
		productStore.saveProductStore(product8);
		productStore.saveProductStore(product9);
		productStore.saveProductStore(product10);
		productStore.saveProductStore(product11);
		productStore.saveProductStore(product12);
		productStore.saveProductStore(product13);
		productStore.saveProductStore(product14);
		productStore.saveProductStore(product15);
		productStore.saveProductStore(product16);
		productStore.saveProductStore(product17);
		productStore.saveProductStore(product18);
		productStore.saveProductStore(product19);
		productStore.saveProductStore(product20);
		productStore.saveProductStore(product21);
		productStore.saveProductStore(product22);
		productStore.saveProductStore(product23);
		productStore.saveProductStore(product24);
		productStore.saveProductStore(product25);
		productStore.saveProductStore(product26);
		productStore.saveProductStore(product27);
		productStore.saveProductStore(product28);
		productStore.saveProductStore(product29);
		productStore.saveProductStore(product30);
		productStore.saveProductStore(product31);
		productStore.saveProductStore(product32);
		productStore.saveProductStore(product33);
		productStore.saveProductStore(product34);
		productStore.saveProductStore(product35);
		productStore.saveProductStore(product36);
		productStore.saveProductStore(product37);
		productStore.saveProductStore(product38);
		productStore.saveProductStore(product39);
		productStore.saveProductStore(product40);
		productStore.saveProductStore(product41);
		productStore.saveProductStore(product42);
		productStore.saveProductStore(product43);
		productStore.saveProductStore(product44);
		productStore.saveProductStore(product45);
		productStore.saveProductStore(product46);
		productStore.saveProductStore(product47);
		productStore.saveProductStore(product48);
		productStore.saveProductStore(product49);
		productStore.saveProductStore(product50);
		
        
		
		productStore.searchByName("Bottle");
		productStore.searchByName("Oil");
		productStore.searchByName("Milk");
		productStore.searchByName("Soap");
		productStore.searchByName("Shampoo");
		productStore.searchByName("Rice");
		productStore.searchByName("Wheat");
		productStore.searchByName("Cheese");
		productStore.searchByName("HAir oil");
		productStore.searchByName("Face Cream");
		productStore.searchByName("Talc Powder");
		productStore.searchByName("Sugar");
		productStore.searchByName("Dal");
		productStore.searchByName("Curd");
		productStore.searchByName("paneer");
		productStore.searchByName("sunflower oil");
		productStore.searchByName("cocount oil");
		productStore.searchByName("Hair oil");
		productStore.searchByName("Olive oil");
		productStore.searchByName("Plastic chair");
		productStore.searchByName("BUCKEt");
		productStore.searchByName("container");
		productStore.searchByName("Facewash");
		productStore.searchByName("BODy lotion");
		productStore.searchByName("Hand wash");
		productStore.searchByName("TOothPaste");
		productStore.searchByName("TOoth brush");
		productStore.searchByName("Maida");
		productStore.searchByName("Rava");
		
		
		productStore.SearchByUniqueId("1");
		productStore.SearchByUniqueId("2");
		productStore.SearchByUniqueId("3");
		productStore.SearchByUniqueId("4");
		productStore.SearchByUniqueId("5");
		productStore.SearchByUniqueId("6");
		productStore.SearchByUniqueId("7");
		productStore.SearchByUniqueId("8");
		productStore.SearchByUniqueId("9");
		productStore.SearchByUniqueId("10");
		
		
		productStore.SearchByUniqueIdAndName("3", "Wheat");
		productStore.SearchByUniqueIdAndName("0", null);
		productStore.SearchByUniqueIdAndName("2", "Cheese");
		productStore.SearchByUniqueIdAndName("5", "HAir oil");
		
		productStore.SearchByUniqueIdAndNameAndOriginCountry("3", "Wheat", "Russia");
		productStore.SearchByUniqueIdAndNameAndOriginCountry("3", "CornFlakes", "bangladesh");
		productStore.SearchByUniqueIdAndNameAndOriginCountry("3", "Honey", "pakistan");

		
		productStore.checkWarrantyExpiredByUniqueId("2");
		productStore.checkWarrantyExpiredByUniqueId("7");
		productStore.checkWarrantyExpiredByUniqueId("8");
		
		
		
		productStore.displayAllProducts();
		
		productStore.getAllByType(ProductType.COSMETICS);
		}
}